[package]
name = "dnd_spreadsheet"
version = "0.1.0"
edition = "2024"

[dependencies]
plex = "0.3.1"
iced = {version = "0.14.0", features=["webgl", "web-colors"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
